name: greenlife
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- DEPENDENCIAS VISUALES ---
  cupertino_icons: ^1.0.8

  # --- FASE 1: AUTENTICACIÓN ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # --- FASE 2: GESTIÓN DE PLANTAS ---
  firebase_storage: ^12.3.2  # Para subir fotos
  uuid: ^4.5.1               # Para nombres únicos de archivos
  image_picker: ^1.1.2       # Para abrir cámara/galería
  intl: ^0.17.0              # Para formatear fechas


  # --- FASE 3 & 4 (FUTURAS - COMENTADAS TEMPORALMENTE) ---
  # Descomenta estas líneas cuando lleguemos a esas fases.
  firebase_messaging: ^15.1.3
  # google_maps_flutter: ^2.10.0
  # geolocator: ^13.0.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true