name: greenlife
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
 

  firebase_storage: ^12.3.2  # Para subir fotos
  uuid: ^4.5.1               # Para nombres únicos de archivos
  image_picker: ^1.1.2       # Para abrir cámara/galería
  intl: ^0.17.0              # Para formatear fechas



  firebase_messaging: ^15.1.3
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1
  http: ^1.2.0
  sensors_plus: ^6.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
